name: Deploy SSIS Packages to SQL Server

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history
          submodules: true  # Include submodules if applicable
          lfs: true  # Include Git LFS files if applicable

      - name: Debug workspace and user
        shell: powershell
        run: |
          Write-Output "Workspace path: ${{ github.workspace }}"
          Write-Output "Current user: $env:USERDOMAIN\$env:USERNAME"
          Write-Output "Directory tree of workspace:"
          tree "${{ github.workspace }}" /F
          Write-Output "Listing all files recursively:"
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse

      - name: List all .dtproj files under workspace
  shell: powershell
  run: |
    Write-Output "GITHUB_WORKSPACE = $env:GITHUB_WORKSPACE"
    Write-Output "Searching for .dtproj files under $env:GITHUB_WORKSPACE..."
    Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Recurse -Filter *.dtproj | ForEach-Object {
      Write-Output "✅ Found: $($_.FullName)"
    }

      - name: List all .ispac files under temp directory
        shell: powershell
        run: |
          Write-Output "Searching for .ispac files in runner temp directory..."
          $tempDir = "${{ runner.temp }}"
          $ispacFiles = Get-ChildItem -Path $tempDir -Filter *.ispac -Recurse
          if ($ispacFiles) {
            $ispacFiles | ForEach-Object { Write-Output $_.FullName }
          } else {
            Write-Output "No .ispac files found in temp directory."
          }

      - name: Verify SSIS project file exists
        shell: powershell
        run: |
          $projectFile = [System.IO.Path]::Combine($env:GITHUB_WORKSPACE, "HandsOnProject", "Timesheets", "TimesheetMigrationnew.dtproj")
          Write-Output "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          Write-Output "Checking for SSIS project file at: $projectFile"
          if (-not (Test-Path "$projectFile")) {
            Write-Error "SSIS project file not found at: $projectFile"
            Write-Output "Listing all .dtproj files in workspace for debugging:"
            $dtprojFiles = Get-ChildItem -Path "$env:GITHUB_WORKSPACE" -Filter *.dtproj -Recurse
            if ($dtprojFiles) {
              $dtprojFiles | ForEach-Object { Write-Output $_.FullName }
            } else {
              Write-Output "No .dtproj files found in workspace."
            }
            exit 1
          }
          Write-Output "Found SSIS project file at $projectFile"

      - name: Verify SSIS build tools exist
        shell: powershell
        run: |
          if (-not (Test-Path "C:\SSISDevOpsTools\SSISBuild.exe")) {
            Write-Error "SSISBuild.exe not found in C:\SSISDevOpsTools"
            exit 1
          }
          if (-not (Test-Path "C:\Program Files\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe")) {
            Write-Error "ISDeploymentWizard.exe not found"
            exit 1
          }
          if (-not (Get-Command sqlcmd.exe -ErrorAction SilentlyContinue)) {
            Write-Error "sqlcmd.exe not found"
            exit 1
          }
          Write-Output "All required tools found."

      - name: Build SSIS Project
        shell: powershell
        run: |
          $projectFile = [System.IO.Path]::Combine($env:GITHUB_WORKSPACE, "HandsOnProject", "Timesheets", "ProjectPackages", "TimesheetMigrationnew.dtproj")
          $outputDir = "${{ runner.temp }}\SSISOutput"
          $config = "Development"
          Write-Output "Building SSIS project at: $projectFile"
          if (-not (Test-Path $outputDir)) {
            New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
          }
          & "C:\SSISDevOpsTools\SSISBuild.exe" -p:"$projectFile" -o:"$outputDir" -c:"$config" -l:DIAG
          $ispacPath = Join-Path $outputDir "$config\TimesheetMigrationnew.ispac"
          if (-not (Test-Path $ispacPath)) {
            Write-Error "Build failed: .ispac file not found at $ispacPath"
            exit 1
          }
          Write-Output "Build succeeded: $ispacPath"

      - name: Deploy SSIS Project via stored procedure
        shell: powershell
        run: |
          $ispacPath = "${{ runner.temp }}\SSISOutput\Development\TimesheetMigrationnew.ispac"
          $sqlServer = "SAMBE202519"
          $catalogDB = "SSISDB"
          $folderName = "TimesheetMigrationnew"
          $projectName = "TimesheetMigrationnew"
          Write-Output "Reading .ispac file from $ispacPath"
          if (-not (Test-Path $ispacPath)) {
            Write-Error ".ispac file not found at: $ispacPath"
            exit 1
          }
          $projectBytes = [System.IO.File]::ReadAllBytes($ispacPath)
          $connString = "Data Source=$sqlServer;Initial Catalog=$catalogDB;Integrated Security=SSPI;"
          $conn = New-Object System.Data.SqlClient.SqlConnection $connString
          $conn.Open()
          $cmd = $conn.CreateCommand()
          $cmd.CommandText = "[catalog].[deploy_project]"
          $cmd.CommandType = [System.Data.CommandType]::StoredProcedure
          $p1 = $cmd.Parameters.Add("@folder_name", [System.Data.SqlDbType]::NVarChar, 128)
          $p1.Value = $folderName
          $p2 = $cmd.Parameters.Add("@project_name", [System.Data.SqlDbType]::NVarChar, 128)
          $p2.Value = $projectName
          $p3 = $cmd.Parameters.Add("@project_stream", [System.Data.SqlDbType]::VarBinary, -1)
          $p3.Value = $projectBytes
          try {
            Write-Output "Deploying project..."
            $cmd.ExecuteNonQuery() | Out-Null
            Write-Output "Deployment succeeded!"
          }
          catch {
            Write-Error "Deployment failed: $_"
            exit 1
          }
          finally {
            $conn.Close()
          }
