name: Deploy Timesheet

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy-database:
    runs-on: windows-latest # Windows runner for sqlcmd
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install SQL Server command-line tools (sqlcmd)
      - name: Install sqlcmd
        run: |
          choco install sqlserver-cmdlineutils -y --no-progress
        shell: powershell

      # Check SQL Server version
      - name: Check SQL Server Connection
        env:
          SQL_SERVER: ${{ secrets.TimesheetDB_SQL_SERVER_PUBLIC_URL }}
          SQL_USER: ${{ secrets.TimesheetDB_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.TimesheetDB_SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.TimesheetDB_SQL_DATABASE }}
        run: |
          sqlcmd -S $env:SQL_SERVER -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE -Q "SELECT @@VERSION;" -o sql_version.txt
          Get-Content sql_version.txt
        shell: powershell

      # Execute SQL script to deploy TimesheetDB with error logging
      - name: Deploy Database
        env:
          SQL_SERVER: ${{ secrets.TimesheetDB_SQL_SERVER_PUBLIC_URL }}
          SQL_USER: ${{ secrets.TimesheetDB_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.TimesheetDB_SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.TimesheetDB_SQL_DATABASE }}
        run: |
          sqlcmd -S $env:SQL_SERVER -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE -i deploy_timesheet.sql -o deploy_output.txt
          Get-Content deploy_output.txt
        shell: powershell
