name: Deploy Timesheet Database
 
on:
  workflow_dispatch:  # Manual trigger
 
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Dev  # Development environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure repository is checked out first
      - name: Deploy SQL to Dev
        uses: ./.github/actions/testing  # Reference the custom action
        with:
          environment: Dev
          sql_server_host: ${{ secrets.DEV_SQL_SERVER_HOST }}
          sql_user: ${{ secrets.DEV_SQL_USER }}
          sql_password: ${{ secrets.DEV_SQL_PASSWORD }}
          db_script: 'create_db_and_table.sql'
          proc_script: 'create_stored_procedure.sql'
