# .github/workflows/main.yml

name: Main Timesheet Setup

on:
  workflow_dispatch:
  
env:
  SQL_SERVER: ${{ secrets.SQL_SERVER_URL }}
  DB_USER: ${{ secrets.DB_USERNAME }}
  DB_PASS: ${{ secrets.DB_PASSWORD }}

jobs:
  setup-db:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQL Server tools
        run: |
         curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Create TimesheetDB and tables
        run: |
          sqlcmd -S "$SQL_SERVER" -U "$DB_USER" -P "$DB_PASS" -Q "CREATE DATABASE TimesheetDB"
          sqlcmd -S "$SQL_SERVER" -U "$DB_USER" -P "$DB_PASS" -d TimesheetDB -i SQL_Script/SQL.sql

  call-ssis:
    needs: setup-db
    uses: ./.github/workflows/ssis.yml
    secrets: inherit
